In [1]:
import numpy as np
from datascience import *

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Comparison

In [2]:
x = 2
y = 3
x, y

(2, 3)

What is the value of the next line?

In [3]:
x > 1

True

what type is the value of the previous line?

In [4]:
type(x > 1)

bool

In [5]:
2 > 1

True

what is the value of the next line?

In [6]:
x > y

False

what is the value of the next line?

In [7]:
y

3

In [8]:
y >= 3

True

what is the value of the next line?

In [9]:
x == y

False

can someone tell us what the next line is doing, and then what the value of the expression would be?

In [10]:
x != 2

False

In [11]:
2 != 2

False

Multiple comparisons

In [12]:
2 < x < 5

False

In [13]:
-1 * x < -1 * y

False

### Comparing strings

What do we think `"dog" > "cat"` will return?

In [14]:
"dog" > "cat"

True

In [15]:
"zack" > "adam"

True

In [16]:
"cat" < "dog"

True

Why is this the case?

What about strings that start the same substring?

In [17]:
"dogma" > "dog"

True

In [19]:
"dogma" > "eog"

False

### Comparisions to arrays

In [20]:
range_between_one_twenty = np.arange(1, 20)
range_between_one_twenty

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
np.arange(2,40,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [22]:
range_between_one_twenty * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [23]:
range_between_one_twenty > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [24]:
range_between_one_twenty

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [25]:
range_between_one_twenty == 19

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,  True], dtype=bool)

back to slides

### Combining comparisons


In [ ]:
a = True
b = False
a, b

In [ ]:
a or b

In [ ]:
not a, not b

In [ ]:

#True and (not False)
#True and True
a and not b

In [ ]:
x, y

In [ ]:
x > 2 or y > 2

In [ ]:
x > 2 and y > 2

In [ ]:
not (x > 2 or y > 2)

back to slides
### Aggregating Comparisons

In [26]:
range_between_one_twenty

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
range_between_one_twenty

#### Modulo operator

In [27]:
6 % 2 == 0

True

In [28]:
6 % 2 

0

Lets find the number of values that are even

In [29]:
# Lets first make a function that tells us if a number is even
def is_even(x):
    """ Converts numbers into bool based on whether the number is even or odd
    hint: modulo 2
    """
    return x % 2 == 0

Let's test if this function works:

In [30]:
is_even(2), is_even(5), is_even(-4)
# T, F, T

(True, False, True)

Now let's apply this function to our array (either make a new table and use `apply` or pass it to our function)


In [31]:
range_between_one_twenty

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [32]:
is_even(range_between_one_twenty)

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [33]:
range_between_one_twenty

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

so how many of these are even?

In [34]:
sum(is_even(range_between_one_twenty))

9

In [35]:
t = Table().with_columns('number', range_between_one_twenty)
t = t.with_columns('is_even', t.apply(is_even, 'number'))
t

number | is_even
1      | False
2      | True
3      | False
4      | True
5      | False
6      | True
7      | False
8      | True
9      | False
10     | True
... (9 rows omitted)

Now how many of these numbers are even?

In [3]:
# solution below

In [36]:
sum(t.column('is_even'))

9

(back to slides)
# Control Statements

In [39]:
def sign(x):
    '''
    Returns "positive", "negative", "zero" depending on the value of x
    note to Adam: only use if's
    '''
    return_string = ""
    if x > 0:
        return_string = "positive"
    if x < 0:
        return_string = "negative"
    if x == 0:
        return_string = "zero"
    return return_string

In [40]:
sign(10), sign(-10), sign(0)
# "positive", "neative", "zero

('positive', 'negative', 'zero')

### `if`, `elif`, and `else`

In [42]:
def sign(x):
    '''
    Returns "positive", "negative", "zero" depending on the value of x
    '''
    return_string = ""
    if x > 0:
        return_string = "positive"
    elif x < 0:
        return_string = "negative"
    else:
        return_string = "zero"
    return return_string

In [43]:
sign(10), sign(-10), sign(0)
# "positive", "negative", "zero

('positive', 'negative', 'zero')

### `abs()`
Now try implementing the `abs()` function

In [44]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [52]:
def abs(x):
    if x < 0:
       x = x * -1
    return x

In [53]:
abs(-1), abs(1), abs(-0.5), abs(0.5)
# 1, 1, 0.5, 0.5

(1, 1, 0.5, 0.5)

In [47]:
type(abs)

builtin_function_or_method

In [49]:
type(abs)

function

(back to slides)
# Random Selection

In [54]:
groups = make_array('treatment', 'control')
groups

array(['treatment', 'control'],
      dtype='<U9')

Let's randomly assign 1 individual to each group

In [61]:
np.random.choice(groups)

'treatment'

In [63]:
np.random.choice(groups, 10)

array(['control', 'treatment', 'treatment', 'treatment', 'control',
       'treatment', 'treatment', 'treatment', 'treatment', 'control'],
      dtype='<U9')

How can we determine how many ppl are in the control group?

In [83]:
randos = np.random.choice(groups, 10)
randos
sum(randos == 'control')


3

In [81]:
randos == 'control'

array([False,  True,  True, False,  True, False, False, False, False,  True], dtype=bool)

In [82]:
sum(randos == 'control')

4

In [71]:
randos

'control'

In [69]:
range_between_one_twenty > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [97]:
randos = np.random.choice(groups, 10)
sum(randos == 'control')

5

lets keep track of how many people are in the contrl group?

In [98]:
make_array(7,5,6,5,5)

array([7, 5, 6, 5, 5])

In [99]:
number_of_control = make_array()
number_of_control

array([], dtype=float64)

In [100]:
len(number_of_control)

0

In [114]:
randos = np.random.choice(groups, 10)
number_assigned_to_control = sum(randos == 'control')

number_of_control = np.append(number_of_control, number_assigned_to_control)
number_of_control

array([ 9.,  2.,  6.,  4.,  4.,  8.,  5.,  5.,  5.,  7.,  5.])

Let's randomly assign 5 individuals to each group

Let's repeat this

Do we see any differences?

So now let's store the outcome

back to slides
# Appending arrays: `np.append()`

Adding an individual to a control or treament group

In [ ]:
# Make an empty array for the control and treatment groups
control_group = make_array()
treatment_group = make_array
control_group, treatment_group

Now let's randomly assign an individual to a group and then add the individual to the corresponding group based on the random assignment

In [ ]:
assigned_group =  ... # randomly choose a value from `groups`
individual = "Person 1"
# check what the value of assigned group is and add the individual to the correspodning group
if ...:
    ...
else:
    ...

control_group, treatment_group

#### Let's put this control statment into a function:
- What should we name the function? 
- What are the arguments/parameters of the function?
- What should the function return?

In [ ]:
def ...(...):
    ...
    return ...

In [ ]:
# example below

In [ ]:
def add_individual_to_group(treatment_group, control_group, individual):
    assigned_group =  np.random.choice(groups)
    print(assigned_group)
    if assigned_group == 'treatment':
        treatment_group = np.append(treatment_group, individual)
    else:
        control_group = np.append(control_group, individual)
    return treatment_group, control_group

Now let's call this function 5 times to assign 5 individuals to the different groups

In [ ]:
control_group = make_array()
treatment_group = make_array()
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 0)
treatment_group, control_group

In [ ]:
# add individual 1

In [ ]:
# add individual 2

In [ ]:
# add individual 3

In [ ]:
# add individual 4

We will now see a cleaner way to assign 5 individuals to the different groups
(back to slides)
<br><br><br><br><br>
# `For` Statements

In [ ]:
for i in np.arange(4):
    print('iteration', i)

Use a `for` loop to assign the individuals to the different groups

# Heads or Tails Experiment

Let's run 10 experiments where we flip a coin 100 times and see how many times we get heads

Before we begin, let's write out all the steps we need to do

*Hint: Lets work inside out, i.e. lets first write code for one experiment*

1. 
2.

In [ ]:
coins = make_array('heads', 'tails')
coins

Let's plot the results from the experiments. What type of plot should we use?

How many times did we get 40 through 60 heads? What percentage of our simulations do these represent?

In [ ]:
1. Make our coins options

(back to slides)

# Monty Hall Simulation

Lets make an array of what can be behind each door

In [ ]:
goats = make_array('first goat', 'second goat')
hidden_behind_door = ... # Lets add the car

Let's make a choice. We won't choose a door but rather whats behind the door

In [ ]:
# Remember np.random.choice
contestant_choice = ...
contestant_choice

In [ ]:
def other_goat(a_goat):
    ''' Returns the other goat that wasn't chosen
    '''
    ...
    return ...

Let's test `other_goat()`

What happens next? 
Monty chooses the door to show and we have a remaining door

In [ ]:
monty_choice = ...
remaining_door = ...

But remember, these choices are conditioned on what the contestant chose

In [ ]:
if ...: # one option for contest's choice
    ...
elif ...: # second option for contests's choice
    ...
elif ...: # third option for contestants choice
    ...
    
contestant_choice, monty_choice, remaining_door

Let's add this to a function so that we can run many simulations of the game

In [ ]:
def monty_hall():
    '''
    Simulates one run of monty hall.
    Returns values behind contestant_choice, monty_choice, remaining_door
    '''
    ...
    return 

Now let's play this game once

Let's play it another time

#### Let's play this game multiple times
How could we do that based on what we learned in today's lecture?

### Simulations

Let's make a table where we will keep simulations
We want to keep track of the original guess, what was revealed, and what is remaining in the other hidden door

In [ ]:
games = Table(['Guess', 'Revealed', 'Remaining'])

### How could we see what remains for each guess?
what metho dshould we call on the table?

Let's group on the remaining to decide if we should change?