In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Converting Types

In [2]:
float("one point two")

ValueError: could not convert string to float: 'one point two'

In [3]:
float("1.2")

1.2

In [4]:
# Converting floats to int
int(2.3) # -> 2

2

In [7]:
int(2.9999999999999999999999999999999999999)

3

# Tables

In [8]:
Table().read_table("party_affiliation2016.csv")

Income             | Republican% | Democrat% | No leaning%
Below 30,000       | 32          | 60        | 8
30,000 to 39,999   | 47          | 46        | 7
50,000 to 74,999   | 49          | 44        | 6
75,000 to 99,999   | 48          | 44        | 8
40,000 to 49,999   | 47          | 46        | 7
100,000 to 149,999 | 51          | 45        | 4
Above 150,000      | 46          | 48        | 6

**How do we store the table?**

In [10]:
party_affiliations = Table().read_table("party_affiliation2016.csv") 
party_affiliations

Income             | Republican% | Democrat% | No leaning%
Below 30,000       | 32          | 60        | 8
30,000 to 39,999   | 47          | 46        | 7
50,000 to 74,999   | 49          | 44        | 6
75,000 to 99,999   | 48          | 44        | 8
40,000 to 49,999   | 47          | 46        | 7
100,000 to 149,999 | 51          | 45        | 4
Above 150,000      | 46          | 48        | 6

In [11]:
type(party_affiliations)

datascience.tables.Table

### How do we find the number of columns in a table?

In [13]:
party_affiliations.num_columns

4

### How do we find the number of rows in a table?

In [15]:
party_affiliations.num_rows

7

In [17]:
party_affiliations.labels

('Income', 'Republican%', 'Democrat%', 'No leaning%')

In [21]:
party_affiliations.relabeled("Republican%", "R%")

Income             | R%   | Democrat% | No leaning%
Below 30,000       | 32   | 60        | 8
30,000 to 39,999   | 47   | 46        | 7
50,000 to 74,999   | 49   | 44        | 6
75,000 to 99,999   | 48   | 44        | 8
40,000 to 49,999   | 47   | 46        | 7
100,000 to 149,999 | 51   | 45        | 4
Above 150,000      | 46   | 48        | 6

In [22]:
party_affiliations.relabeled(1, "R%")

Income             | R%   | Democrat% | No leaning%
Below 30,000       | 32   | 60        | 8
30,000 to 39,999   | 47   | 46        | 7
50,000 to 74,999   | 49   | 44        | 6
75,000 to 99,999   | 48   | 44        | 8
40,000 to 49,999   | 47   | 46        | 7
100,000 to 149,999 | 51   | 45        | 4
Above 150,000      | 46   | 48        | 6

columns are 0-indexed, meaning that the first index is 0

In [23]:
party_affiliations.relabeled(4, "No Party")

IndexError: tuple index out of range

We tried accessing the 4th column via 4, but how would we access the laat column?

Answer: with 3

## Icecream Cones

## 

In [25]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [27]:
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

Imageine we have 100 columns in our table, now we want 99 of them.

As of now, we'd have to select the 99 ones that we want

A smarter idea is to "drop" the column(s) we dont want

In [30]:
cones.drop('Color')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [31]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [33]:
cones.sort("Price")

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [34]:
help(cones.sort)

Help on method sort in module datascience.tables:

sort(column_or_label, descending=False, distinct=False) method of datascience.tables.Table instance
    Return a Table of rows sorted according to the values in a column.

    Args:
        ``column_or_label``: the column whose values are used for sorting.

        ``descending``: if True, sorting will be in descending, rather than
            ascending order.

        ``distinct``: if True, repeated values in ``column_or_label`` will
            be omitted.

    Returns:
        An instance of ``Table`` containing rows sorted based on the values
        in ``column_or_label``.

    >>> marbles = Table().with_columns(
    ...    "Color", make_array("Red", "Green", "Blue", "Red", "Green", "Green"),
    ...    "Shape", make_array("Round", "Rectangular", "Rectangular", "Round", "Rectangular", "Round"),
    ...    "Amount", make_array(4, 6, 12, 7, 9, 2),
    ...    "Price", make_array(1.30, 1.30, 2.00, 1.75, 1.40, 1.00))
    >>> marbles
  

In [35]:
cones.sort("Price", descending = True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

Q: Is the above, ascedning or descedning order?
A: descending order - going from least to most

In [36]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [37]:
cones.where("Flavor", "chocolate")

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [38]:
# get just the pink cones
cones.where("Color", "pink")

Flavor     | Color | Price
strawberry | pink  | 3.55
strawberry | pink  | 5.25
bubblegum  | pink  | 4.75

In [39]:
cones.sort("Price")

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [40]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [ ]:
cones = cones.sort("Price") # reassinging

In [41]:
cones_sorted = cones.sort("Price")

In [42]:
cones_sorted

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [ ]:
 # sort a table 

In [ ]:
 # conditions. Say we only want ones that are pink

In [ ]:
 # conditions. say we only want ones that are < $5

In [43]:
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers

name                              | material        | city          | height | completed
One World Trade Center            | mixed/composite | New York City | 541.3  | 2014
Willis Tower                      | steel           | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete        | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete        | Chicago       | 423.22 | 2009
Empire State Building             | steel           | New York City | 381    | 1931
Bank of America Tower             | mixed/composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete        | Las Vegas     | 350.22 | 1996
Aon Center                        | steel           | Chicago       | 346.26 | 1973
John Hancock Center               | steel           | Chicago       | 343.69 | 1969
Chrysler Building                 | steel           | New York City | 318.9  | 1930
... (1771 rows omitted)

# Another Table

### How many individuals are in this table

In [44]:
skyscrapers.num_rows

1781

In [45]:
skyscrapers.labels

('name', 'material', 'city', 'height', 'completed')

In [ ]:
 # where city is ...

In [46]:
skyscrapers.where("city", "chicago")

name | material | city | height | completed

In [47]:
skyscrapers.where("City", "Chicago")

ValueError: label "City" not in labels ('name', 'material', 'city', 'height', 'completed')

In [48]:
skyscrapers.where("City", "Chicago")

ValueError: label "City" not in labels ('name', 'material', 'city', 'height', 'completed')

In [49]:
 # where material
skyscrapers.where("material", "steel")

name                  | material | city          | height | completed
Willis Tower          | steel    | Chicago       | 442.14 | 1974
Empire State Building | steel    | New York City | 381    | 1931
Aon Center            | steel    | Chicago       | 346.26 | 1973
John Hancock Center   | steel    | Chicago       | 343.69 | 1969
Chrysler Building     | steel    | New York City | 318.9  | 1930
New York Times Tower  | steel    | New York City | 318.77 | 2007
U.S. Bank Tower       | steel    | Los Angeles   | 310.29 | 1990
Wells Fargo Plaza     | steel    | Houston       | 302.37 | 1983
70 Pine               | steel    | New York City | 290.17 | 1932
One Liberty Place     | steel    | Philadelphia  | 288.04 | 1987
... (700 rows omitted)

In [ ]:
 # where completed

(back to slides)
# Arrays

In [ ]:
 # let's make an array
  # does anyone know how to make an array from the reading?
  # lets make the array be an array of numbers

In [51]:
make_array(0,1,2,3)

array([0, 1, 2, 3])

In [52]:
array1 = make_array(0,1,2,3)
array1

array([0, 1, 2, 3])

In [53]:
array1 + 1

array([1, 2, 3, 4])

In [54]:
array1

array([0, 1, 2, 3])

In [55]:
array1 = array1 + 1

In [56]:
array2 = make_array(5,6,7,8)
array1, array2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [ ]:
 # lets apply different computations to the array

In [57]:
array1 + array2

array([ 6,  8, 10, 12])

performs the operations element-wise, i.e. across coresponding elements in the arrays

In [58]:
array3 = make_array(2,3,4)

In [59]:
array3 + array1

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
 # addition

In [60]:
 # multiplication
array3 * 10

array([20, 30, 40])

In [62]:
 # square
array3 * array3

array([ 4,  9, 16])

In [63]:
array3 ** 2

array([ 4,  9, 16])

In [ ]:
  # absolute value 

In [64]:
make_array(-2,4,-6,4)

array([-2,  4, -6,  4])

In [65]:
array4 = make_array(-2,4,-6,4)

In [66]:
abs(array4)

array([2, 4, 6, 4])

### Array statistics using numpy



In [ ]:
 # np.mean, np.average

In [68]:
np.mean(array4)

0.0

In [69]:
array4

array([-2,  4, -6,  4])

In [70]:
np.median(array4)

1.0

In [72]:
np.abs(array4)

array([2, 4, 6, 4])

In [73]:
make_array(0,1,2,3,4,5,6,7,8,9,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Ranges

In [75]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [76]:
# start value is inclusive, end value is exclusive
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [77]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [81]:
# start at 100, go backwards by 1 until we hit 2
np.arange(100,2,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3])

In [ ]:
  #np.arrange(end), np.arrange(start, end), step

In [87]:
max(skyscrapers.select('height'))

'height'

In [ ]:
Why did we not get the height of the tallest building in the above code?



In [90]:
skyscrapers.select('height')

height
541.3
442.14
425.5
423.22
381
365.8
350.22
346.26
343.69
318.9
... (1771 rows omitted)

In [92]:
skyscrapers.column('height')

array([ 541.29998779,  442.14001465,  425.5       , ...,   44.5       ,
         44.5       ,   43.88999939])

In [93]:
max(skyscrapers.column('height'))

541.29998779297

In [88]:
max(make_array(1,24,5))

24

In [91]:
type(make_array(1,24,5))

numpy.ndarray

# Questions

**Question 1:** Given a file callled `nba_salaries.csv`, how can we load it into a `Table`?

In [94]:
Table.read_table("nba_salaries.csv")

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [95]:
nba = Table.read_table("nba_salaries.csv")

**Question 2:** What are the columns in our table?

In [97]:
nba.num_columns

6

**Question 3**: Create an array containing the names of all centers (C) who make more than $15M/year

*Hint:* break this into two steps

In [101]:
centers = nba.where('position', 'C')

In [103]:
help(centers.where)

Help on method where in module datascience.tables:

where(column_or_label, value_or_predicate=None, other=None) method of datascience.tables.Table instance
    Return a new ``Table`` containing rows where ``value_or_predicate``
    returns True for values in ``column_or_label``.

    Args:
        ``column_or_label``: A column of the ``Table`` either as a label
        (``str``) or an index (``int``). Can also be an array of booleans;
        only the rows where the array value is ``True`` are kept.

        ``value_or_predicate``: If a function, it is applied to every value
        in ``column_or_label``. Only the rows where ``value_or_predicate``
        returns True are kept. If a single value, only the rows where the
        values in ``column_or_label`` are equal to ``value_or_predicate``
        are kept.

        ``other``: Optional additional column label for
        ``value_or_predicate`` to make pairwise comparisons. See the
        examples below for usage. When ``other`` is

In [105]:
centers.where('salary', are.above(15000000))

rank | name             | position | team               | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat         | 15004000 | 2000
2    | Shaquille O'Neal | C        | Los Angeles Lakers | 19285000 | 2001
3    | Alonzo Mourning  | C        | Miami Heat         | 16879000 | 2001
5    | Hakeem Olajuwon  | C        | Houston Rockets    | 16685000 | 2001
2    | Shaquille O'Neal | C        | Los Angeles Lakers | 21428000 | 2002
3    | Alonzo Mourning  | C        | Miami Heat         | 18756000 | 2002
2    | Shaquille O'Neal | C        | Los Angeles Lakers | 23571000 | 2003
3    | Shawn Kemp       | C        | Orlando Magic      | 21500000 | 2003
8    | Dikembe Mutombo  | C        | New Jersey Nets    | 16105000 | 2003
... (115 rows omitted)

In [108]:
centers.where('salary', are.above(15000000)).column('name')

array(["Shaquille O'Neal", 'Alonzo Mourning', "Shaquille O'Neal",
       'Alonzo Mourning', 'Hakeem Olajuwon', "Shaquille O'Neal",
       'Alonzo Mourning', "Shaquille O'Neal", 'Shawn Kemp',
       'Dikembe Mutombo', "Shaquille O'Neal", 'Dikembe Mutombo',
       'Chris Webber', "Shaquille O'Neal", 'Dikembe Mutombo',
       'Chris Webber', "Shaquille O'Neal", 'Chris Webber',
       "Jermaine O'Neal", 'Tim Duncan', "Shaquille O'Neal",
       "Jermaine O'Neal", 'Tim Duncan', "Shaquille O'Neal",
       "Jermaine O'Neal", 'Tim Duncan', "Jermaine O'Neal",
       "Shaquille O'Neal", 'Tim Duncan', "Amar'e Stoudemire", 'Yao Ming',
       "Jermaine O'Neal", 'Tim Duncan', "Shaquille O'Neal",
       "Amar'e Stoudemire", 'Yao Ming', 'Dwight Howard', 'Tim Duncan',
       'Yao Ming', 'Dwight Howard', "Amar'e Stoudemire", 'Tim Duncan',
       "Amar'e Stoudemire", 'Dwight Howard', "Amar'e Stoudemire",
       'Andrew Bynum', "Amar'e Stoudemire", 'Dwight Howard',
       'Dwight Howard', 'Marc Gasol', 'Br

In [111]:
centers.where("name", "Jermaine O'Neal")

rank | name            | position | team                   | salary   | season
46   | Jermaine O'Neal | C        | Portland Trail Blazers | 5075000  | 2000
70   | Jermaine O'Neal | C        | Indiana Pacers         | 5700000  | 2001
64   | Jermaine O'Neal | C        | Indiana Pacers         | 6325000  | 2002
61   | Jermaine O'Neal | C        | Indiana Pacers         | 6950000  | 2003
7    | Jermaine O'Neal | C        | Indiana Pacers         | 16440000 | 2006
4    | Jermaine O'Neal | C        | Indiana Pacers         | 18084000 | 2007
4    | Jermaine O'Neal | C        | Indiana Pacers         | 19728000 | 2008
3    | Jermaine O'Neal | C        | Toronto Raptors        | 21372000 | 2009
2    | Jermaine O'Neal | C        | Miami Heat             | 23016000 | 2010
125  | Jermaine O'Neal | C        | Boston Celtics         | 5765000  | 2011
... (3 rows omitted)

# Visualization

(week 3)

In [ ]:
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers

In [ ]:
skyscrapers.scatter('height', 'completed') # scatter, plot needs numbers

In [ ]:
skyscrapers.barh('city')

In [ ]:
skyscrapers.hist('completed')