In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Table Questions

**Question 1:** Given a file callled `nba_salaries.csv`, how can we load it into a `Table`?

In [2]:
nba = Table.read_table("nba_salaries.csv")
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [5]:
# this line will give us a new table with one column nba.select('salary')

nba.column('salary')

array([17142000, 16806000, 15004000, ...,   183115,   183115,   155647])

In [6]:
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [13]:
nba.take(1)

rank | name          | position | team                   | salary   | season
2    | Kevin Garnett | PF       | Minnesota Timberwolves | 16806000 | 2000

In [14]:
nba.take(0)

rank | name             | position | team               | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000

In [15]:
nba.take(0,1,2,3,4)

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000

In [ ]:
nba.take(0,1,2,3,4,5,6,7,8,9,10) # BAD IDEA< DONT DO THIS

In [16]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nba.take(np.arange(0,5))

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000

how can we rearrange the table above so that SHawn Kemp is first, and Shaq is last?

In [20]:
nba.take(2,0)

rank | name             | position | team               | salary   | season
3    | Alonzo Mourning  | C        | Miami Heat         | 15004000 | 2000
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000

In [21]:
nba.take(0,0,0,0)

rank | name             | position | team               | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000

#### how do we get the last ten rows in our table? (in ascending order)

In [25]:
#1. create a range
indices = np.arange(nba.num_rows, nba.num_rows-10,-1)
nba.take(indices)


IndexError: index 9456 is out of bounds for axis 0 with size 9456

In [26]:
nba.num_rows

9456

In [27]:
nba.take(0)

rank | name             | position | team               | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000

In [29]:
nba.take(nba.num_rows-1)

rank | name          | position | team                  | salary | season
528  | Luguentz Dort | SG       | Oklahoma City Thunder | 155647 | 2020

In [33]:
indices = np.arange(nba.num_rows-1, nba.num_rows-11,-1)
nba.take(indices)

rank | name                  | position | team                  | salary | season
528  | Luguentz Dort         | SG       | Oklahoma City Thunder | 155647 | 2020
527  | Tyler Johnson         | SG       | Phoenix Suns          | 183115 | 2020
526  | Anthony Tolliver      | PF       | Memphis Grizzlies     | 183115 | 2020
525  | Jontay Porter         | PF       | Memphis Grizzlies     | 197933 | 2020
524  | Jimmer Fredette       | G        | Phoenix Suns          | 208509 | 2020
523  | Tyler Zeller          | C        | San Antonio Spurs     | 245686 | 2020
522  | Ky Bowman             | PG       | Golden State Warriors | 350189 | 2020
521  | Juan Toscano-Anderson | SF       | Golden State Warriors | 350189 | 2020
520  | Norvel Pelle          | SF       | Philadelphia 76ers    | 350189 | 2020
519  | Dion Waiters          | SG       | Miami Heat            | 375385 | 2020

# **Question 2:** What are the columns in our table?

In [3]:
nba.labels

('rank', 'name', 'position', 'team', 'salary', 'season')

**Question 3**: Find the names of all centers (C) who make more than $15M/year

*Hint:* break this into two steps

**Question 4**: Which player had the highest salary in 2015?

*Hint:* how do we access an individual (row) in a Table

1. find al rows in 2015 season
2. sort the rows by salary (in descidning)
3. get the name at the first row

1. sort the rows by salary (in ascending order)
2. find all rows in 2015 season
3. get the name at the last row

In [37]:
nba_2015 = nba.where("season", 2015)
nba_2015

rank | name            | position | team                  | salary   | season
1    | Kobe Bryant     | SF       | Los Angeles Lakers    | 23500000 | 2015
2    | Joe Johnson     | G        | Brooklyn Nets         | 23180790 | 2015
3    | Carmelo Anthony | PF       | New York Knicks       | 22458401 | 2015
4    | Dwight Howard   | C        | Houston Rockets       | 21436271 | 2015
5    | Chris Bosh      | PF       | Miami Heat            | 20644400 | 2015
6    | LeBron James    | SF       | Cleveland Cavaliers   | 20644400 | 2015
7    | Chris Paul      | PG       | LA Clippers           | 20068563 | 2015
8    | Deron Williams  | PG       | Brooklyn Nets         | 19754465 | 2015
9    | Rudy Gay        | SF       | Sacramento Kings      | 19317326 | 2015
10   | Kevin Durant    | SF       | Oklahoma City Thunder | 18995624 | 2015
... (517 rows omitted)

In [40]:
nba_sorted= nba_2015.sort('salary', descending=True)

nba_sorted.select("name").take(0)
#highest_paid = ...
# this gets us the answer as a table with one row and one column, but what we want is a string

name
Kobe Bryant

In [44]:
highest_paid = nba_sorted.column("name").item(0)
highest_paid

'Kobe Bryant'

In [ ]:
# skip

In [ ]:
# skip

In [ ]:
# skip

**Question:** What type is returned by `take()`?

# Arrays

In [ ]:
 # let's make an array
  # does anyone know how to make an array from the reading?
  # lets make the array be an array of numbers

#### lets apply different computations to the array

In [ ]:
 # addition

In [ ]:
 # multiplication

In [ ]:
 # square

In [ ]:
  # absolute value 

In [ ]:
make_array(1,2,34)

In [ ]:
aa = make_array(1,2,3,4)
aa

In [ ]:
# find the sum of all values in an array

In [ ]:
# find the maximum value in the array

In [ ]:
# find the minimum value

In [ ]:
# find the first item in an array
# note to Adam (dont use index slicing)


# Ranges

In [ ]:
  #np.arrange(end), np.arrange(start, end), step

## Array statistics using numpy
(look at end of array's in python reference)

In [ ]:
# np.mean, np.average

In [ ]:
# absolute

(back to slides)
# Census

In [45]:
data_url = "https://www2.census.gov/programs-surveys/popest/datasets/2010-2015/national/totals/nst-est2015-popchg2010_2015.csv"
census = Table.read_table(data_url)
census

SUMLEV | REGION | DIVISION | STATE | NAME             | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | NPOPCHG_2010 | NPOPCHG_2011 | NPOPCHG_2012 | NPOPCHG_2013 | NPOPCHG_2014 | NPOPCHG_2015 | PPOPCHG_2010 | PPOPCHG_2011 | PPOPCHG_2012 | PPOPCHG_2013 | PPOPCHG_2014 | PPOPCHG_2015 | NRANK_ESTBASE2010 | NRANK_POPEST2010 | NRANK_POPEST2011 | NRANK_POPEST2012 | NRANK_POPEST2013 | NRANK_POPEST2014 | NRANK_POPEST2015 | NRANK_NPCHG2010 | NRANK_NPCHG2011 | NRANK_NPCHG2012 | NRANK_NPCHG2013 | NRANK_NPCHG2014 | NRANK_NPCHG2015 | NRANK_PPCHG2010 | NRANK_PPCHG2011 | NRANK_PPCHG2012 | NRANK_PPCHG2013 | NRANK_PPCHG2014 | NRANK_PPCHG2015
10     | 0      | 0        | 0     | United States    | 308758105         | 309346863       | 311718857       | 314102623       | 316427395       | 318907401       | 321418820       | 588758       | 2371994      | 2383766      | 2324772      | 2480006      | 2511419      | 0.190686     | 0.766775     | 0.764717     | 0.740131     | 0.783752     | 0.787507     | X                 | X                | X                | X                | X                | X                | X                | X               | X               | X               | X               | X               | X               | X               | X               | X               | X               | X               | X
20     | 1      | 0        | 0     | Northeast Region | 55318348          | 55387174        | 55638038        | 55835056        | 56019353        | 56171281        | 56283891        | 68826        | 250864       | 197018       | 184297       | 151928       | 112610       | 0.124418     | 0.452928     | 0.354107     | 0.330074     | 0.271206     | 0.200476     | 4                 | 4                | 4                | 4                | 4                | 4                | 4                | 3               | 3               | 3               | 4               | 4               | 4               | 3               | 3               | 3               | 4               | 4               | 4
20     | 2      | 0        | 0     | Midwest Region   | 66929897          | 66977505        | 67156488        | 67340231        | 67565788        | 67762069        | 67907403        | 47608        | 178983       | 183743       | 225557       | 196281       | 145334       | 0.0711311    | 0.267229     | 0.273604     | 0.334951     | 0.290504     | 0.214477     | 3                 | 3                | 3                | 3                | 3                | 3                | 3                | 4               | 4               | 4               | 3               | 3               | 3               | 4               | 4               | 4               | 3               | 3               | 3
20     | 3      | 0        | 0     | South Region     | 114562953         | 114862858       | 116080267       | 117331340       | 118487418       | 119795010       | 121182847       | 299905       | 1217409      | 1251073      | 1156078      | 1307592      | 1387837      | 0.261782     | 1.05988      | 1.07777      | 0.98531      | 1.10357      | 1.15851      | 1                 | 1                | 1                | 1                | 1                | 1                | 1                | 1               | 1               | 1               | 1               | 1               | 1               | 1               | 1               | 1               | 2               | 2               | 1
20     | 4      | 0        | 0     | West Region      | 71946907          | 72119326        | 72844064        | 73595996        | 74354836        | 75179041        | 76044679        | 172419       | 724738       | 751932       | 758840       | 824205       | 865638       | 0.239648     | 1.00492      | 1.03225      | 1.03109      | 1.10848      | 1.15144      | 2                 | 2                | 2                | 2                | 2                | 2                | 2                

### Difference between `select()` and `column()`

In [46]:
census.column(0)

array([10, 20, 20, 20, 20, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40])

In [47]:
census.select(0)

SUMLEV
10
20
20
20
20
40
40
40
40
40
... (47 rows omitted)

**Question:** What's the difference between these two?

Answer: the former is an array of integers, the latter is a table with a single column

### Explore data

In [48]:
census.show(5)
census.num_columns, census.num_rows

(43, 57)

## Exploring the Table
If we look at [this documentation](https://www2.census.gov/programs-surveys/popest/datasets/2010-2015/national/totals/nst-est2015-popchg2010-2015.pdf), we can see a description of the table

In [ ]:
# Lets explore a few of the columns

In [ ]:
 # "REGION"
# Categorical or Numerical?

In [ ]:
 # DIVISION
    # Categorical or Numerical?

In [ ]:
 # STATE
    # Categorical or Numerical?

In [ ]:
 # NAME
    # Categorical or Numerical?

## Selecting a few columns of interest

Lets look at the "NAME", "STATE", "REGION", "2013 Estimate", "2014 Estimate"

In [ ]:
partial_census = census.select(...)

In [ ]:
# Relabel columns

# Column Arithmetic 

Difference between 13 and 13 estimate

In [ ]:
change = ...
change

## Make new table with change

In [ ]:

# Hint, use with_columns

### Reformatter

In [ ]:
## Reformat these changes
# NumberFormatter, PercentFormatter
# set_format

### Interpretting these changes

**Are these changes meaningful?**

In [ ]:
 # Convert changes to percentages

In [ ]:
# Let's look at larger ranges in time, we might see more changes then

# Analyzing the results/table

In [ ]:
# find the regiion with the largest total change

In [ ]:
# demonstrate rows

In [ ]:
# find the regiion with the largest percentage change

In [ ]:
# add anual growth based on total growth